# Basics of Python

In [14]:
# concat
s1='ATCGA'
print(s1+"TCAGCA")

num_A=s1.count('A')
print(num_A)

ATCGATCAGCA
2


In [38]:
# generate lists, arrays
ex_list=[1,2,3]
ex_tuple=(1,2,"Rob")

# index values
print(ex_list[2])
print(ex_tuple[2])

3
Rob


In [39]:
# numpy is bae
import numpy as np
print(np.sin(2))

ex_array = np.array([1,2,3,4])
print(ex_array*2)
print(np.dot(ex_array,ex_array))

ex_2darray = np.array([[1,2,3,4],[1,2,3,4]])
print(ex_2darray)

0.9092974268256817
[2 4 6 8]
30
[[1 2 3 4]
 [1 2 3 4]]


In [54]:
# auto generation 
ex_linspace = np.linspace(0,10,100) # linearly spaced: start 0, end 10, contains 100 points
ex_logspace = np.logspace(-1,1,10) # log spaced: start 10^-1, end 10^1, w 10 points
ex_arange = np.arange(0,50,2) # range: start 0, end 50, step size 2 

len(ex_arange)

25